#pragma once
//////////////////////////////////////////////////////////////////////////////
// BILL PART
#define GROUND_Y 300.0f
#define Bill_GRAVITY 0.002f
#define BILL_RUN_SPEED  0.1f
#define BILL_JUMP_SPEED_Y 0.5f

#define BILL_STATE_IDLE 100
#define BILL_STATE_SWIM 200
#define BILL_STATE_RUN 300
#define BILL_STATE_JUMP 400
#define BILL_STATE_LAYDOWN 500
#define BILL_STATE_DEAD 600
#define BILL_STATE_SWIM_MOVE 700


#pragma once ANIMATION_ID
#define ID_ANI_BILL_IDLE_RIGHT 100
#define ID_ANI_BILL_IDLE_SHOT_UP_RIGHT 101
#define ID_ANI_BILL_IDLE_LEFT 150
#define ID_ANI_BILL_IDLE_SHOT_UP_LEFT 151
#define ID_ANI_BILL_SWIMMING_RIGHT 200
#define ID_ANI_BILL_SWIMMING_SHOT_RIGHT 201
#define ID_ANI_BILL_SWIMMING_SHOT_UP_RIGHT 202
#define ID_ANI_BILL_SWIMMING_SHOT_UP_STAND_RIGHT 203
#define ID_ANI_BILL_SWIMMING_LEFT 250
#define ID_ANI_BILL_SWIMMING_SHOT_LEFT 251
#define ID_ANI_BILL_SWIMMING_SHOT_UP_LEFT 252
#define ID_ANI_BILL_SWIMMING_SHOT_UP_STAND_LEFT 253
#define ID_ANI_BILL_SWIMMING_START 299
#define ID_ANI_BILL_RUN_RIGHT 300
#define ID_ANI_BILL_RUN_SHOT_RIGHT 301
#define ID_ANI_BILL_RUN_SHOT_UP_RIGHT 302
#define ID_ANI_BILL_RUN_SHOT_DOWN_RIGHT 303
#define ID_ANI_BILL_RUN_LEFT 350
#define ID_ANI_BILL_RUN_SHOT_LEFT 351
#define ID_ANI_BILL_RUN_SHOT_UP_LEFT 352
#define ID_ANI_BILL_RUN_SHOT_DOWN_LEFT 353
#define ID_ANI_BILL_JUMP_RIGHT 400
#define ID_ANI_BILL_JUMP_LEFT 450
#define ID_ANI_BILL_LAYDOWN_RIGHT 500
#define ID_ANI_BILL_LAYDOWN_LEFT 550
#define ID_ANI_BILL_DEAD 600

#define TEXTURE_RIGHT_PATH L"./Resources/Images/bill_animation.png"
#define TEXTURE_RIGHT_ID 0
#define TEXTURE_LEFT_ID 1
#pragma once ANIMATION_DURATION
#define DURATION_ANI_BILL_IDLE 20
#define DURATION_ANI_BILL_SWIMMING 100
#define DURATION_ANI_BILL_RUN 100
#define DURATION_ANI_BILL_JUMP 100
////////////////////////////////////////////////////////////////////////
//BULLETPART
#define ID_BULLET_TEXTURE 2
#define TEXTURE_BULET_PATH  L"./Resources/Images/Bullets.png"
//Bullet go from 1000 to 1100
#define ID_ANI_BULLET_NORMAL 1000
#define ID_ANI_BULLET_L 1001
#define ID_ANI_BULLET_F 1002
#define ID_ANI_BULLET_S 1003
#define ID_ANI_BULLET_RIFLE 1004

#define RECOID_TIME 100
///////////////////////////////////////////////////////////////////////
// Sodier
#define TEXTURE_SODIER_ID 3
#define SODIER_STATE_RUNNING 2100
#define SODIER_STATE_JUMPING 2110
#define SODIER_STATE_DEATH 2120
#define SODIER_STATE_SHOTED 2130
#define SODIER_STATE_SHOT 2140
#define SODIER_STATE_LAYDOWN 2140

#define ID_ANI_SODIER_RUNNING 2100
#define ID_ANI_SODIER_JUMPING 2110
#define ID_ANI_SODIER_SHOTED 2130
#define ID_ANI_SODIER_DEATH 2120
#define ID_ANI_SODIER_SHOT 2140
#define ID_ANI_SODIER_LAYDOWN 2150
//Sniper
#define TEXTURE_SNIPER_ID 7
#define SNIPER_STATE_HIDDEN 2200
#define SNIPER_STATE_SHOT 2210
#define SNIPER_STATE_SHOTED 2230
#define SNIPER_STATE_DIE 2240
#define SNIPER_STATE_NORMAl 2250

#define ID_ANI_SNIPER_SHOT 2210
#define ID_ANI_SNIPER_SHOT_UP 2211
#define ID_ANI_SNIPER_SHOT_DOWN 2212
#define ID_ANI_SNIPER_HIDDEN 2200
#define ID_ANI_SNIPER_SHOW 2230
#define ID_ANI_SNIPER_HIDDEN_SHOT 2240
#define ID_ANI_SNIPER_NORMAL 2250


//GunRotation
#define TEXTURE_GUNROTATION_ID 4
#define GUNROTATION_STATE_HIDDEN 2000
#define GUNROTATION_STATE_NORMAL 2010
#define GUNROTATION_STATE_DIE 2099

#define ID_ANI_GUNROTATION_HIDDEN 2000
#define ID_ANI_GUNROTATION_SHOW 2005
#define ID_ANI_GUNROTATION_SHOT_0 2010
#define ID_ANI_GUNROTATION_SHOT_1 2015
#define ID_ANI_GUNROTATION_SHOT_2 2020
#define ID_ANI_GUNROTATION_SHOT_3 2025
#define ID_ANI_GUNROTATION_SHOT_4 2030
#define ID_ANI_GUNROTATION_SHOT_5 2035
#define ID_ANI_GUNROTATION_SHOT_6 2040
#define ID_ANI_GUNROTATION_SHOT_7 2045
#define ID_ANI_GUNROTATION_SHOT_8 2050
#define ID_ANI_GUNROTATION_SHOT_9 2055
#define ID_ANI_GUNROTATION_SHOT_10 2060
#define ID_ANI_GUNROTATION_SHOT_11 2065

///////////////////////////////////////////////////////////////////////
//MISC
#define TEXTURE_GRASS_ID 5
#define ID_GRASS 9999
#define AIRCRAFT_TEXTURE_ID 6
#define PI 3.141517
//////////////////////////////////////////////////////////////////////